// Tekstlagen over de 3D-scène, gekoppeld aan scrollvoortgang (0–1).
// Korte teksten: de animatie vertelt het verhaal, de tekst benoemt alleen de stap.
export const CAPTIONS = [
  {
    id: 'hero',
    start: -0.01,
    end: 0.1,
    layout: 'hero',
    eyebrow: 'Water-zuivering',
    title: 'Zuiver water.\nRecht uit de kraan.',
    text: 'Reis mee met een druppel: van je kraan, door drie filters, terug naar je glas.',
  },
  {
    id: 'journey',
    start: 0.13,
    end: 0.24,
    eyebrow: 'De reis begint',
    title: 'Kraanwater is goed.\nNog niet zuiver.',
    text: 'Sporen van chloor, kalk, PFAS en medicijnresten reizen mee. Kijk waar ze achterblijven.',
  },
  {
    id: 'f1',
    start: 0.26,
    end: 0.38,
    eyebrow: 'Filter 1 · Voorfilter',
    title: 'PPC-filter',
    text: 'Vangt zand, roest en slib op — met poriën van 1 micron, zeventig keer fijner dan een haar.',
    stat: 'Zuiverheid 60%',
  },
  {
    id: 'f2',
    start: 0.4,
    end: 0.52,
    eyebrow: 'Filter 2 · Het hart van het systeem',
    title: 'RO-membraan',
    text: 'Poriën van 0,0001 micron. PFAS, medicijnresten, microplastics en zware metalen komen er niet doorheen.',
    stat: 'Zuiverheid 99%',
    note: 'Alle drie de filters zitten in één apparaat van 10,5 cm breed.',
  },
  {
    id: 'f3',
    start: 0.54,
    end: 0.66,
    eyebrow: 'Filter 3 · Nafilter',
    title: 'CTO-koolstoffilter',
    text: 'Actieve koolstof haalt de allerlaatste smaakjes en geurtjes weg.',
    stat: 'Zuiverheid 100%',
  },
  {
    id: 'minerals',
    start: 0.68,
    end: 0.8,
    highlight: true,
    eyebrow: 'Zuiveren → Mineralen toevoegen → Klaar om te drinken',
    title: 'Mineralen terug\nin het water',
    text: 'Na de zuivering worden calcium en magnesium opnieuw toegevoegd — voor een vol, natuurlijk smaakprofiel.',
  },
  {
    id: 'back',
    start: 0.82,
    end: 0.93,
    eyebrow: 'Terug naar je kraan',
    title: 'Zuiver. Fris.\nKlaar om te drinken.',
    text: 'Elke keer dat je de kraan opendraait — 1,58 liter per minuut, fluisterstil.',
  },
];
